# Matrix and Vector Operations

In [29]:
import numpy as np
from datetime import datetime

## Basic Operations

In [6]:
M = np.array([[1,2],[3,4]])
L = [[1,2],[3,4]]

In [10]:
assert L[0][0] == M[0][0]


Create an array of 10 zeros:

In [8]:
np.zeros(10)

1

Create an array of 10 ones:

In [12]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Create an array of 10 x 10 ones:

In [13]:
np.ones((10,10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

Create an array of 5 x 5 uniformly distributed numbers:

In [15]:
np.random.random((5,5))

array([[ 0.95886113,  0.75395694,  0.66439159,  0.63904281,  0.54576073],
       [ 0.30569077,  0.93624409,  0.63376513,  0.35927285,  0.56314516],
       [ 0.68646356,  0.6444342 ,  0.10702781,  0.50165984,  0.2266222 ],
       [ 0.24237787,  0.82315587,  0.43784844,  0.78961121,  0.55610346],
       [ 0.12921927,  0.47553004,  0.57369418,  0.4474111 ,  0.45041097]])

Create an array of 5 x 5 noramlly distributed numbers:

In [17]:
np.random.randn(5,5)

array([[-0.12708895, -0.09625825,  1.29406283,  0.88251628,  1.2998236 ],
       [ 1.57880319,  0.66623863,  0.16108012,  1.5754845 , -1.49223835],
       [ 1.0732082 ,  1.29761126, -1.15479183, -0.30683734, -1.18654531],
       [-0.59057681, -1.23386525, -1.00966871,  0.29275444, -0.43310669],
       [-0.81904721, -1.25788552, -0.06588317, -0.79677126, -0.24663087]])

Multiply element-wise two 4 x 2 matrices together:

In [18]:
np.random.randn(4,2) * np.random.randn(4,2)

array([[-2.49878041,  0.49667616],
       [ 0.28132226, -0.52295142],
       [ 0.034052  , -0.30021812],
       [-0.00410769,  0.03753431]])

However, this doesn't work if you attempt to multiple the dot product together:

In [19]:
np.dot(np.random.randn(4,2), np.random.randn(4,2))

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

You can, however, transpose the second matrix to conduct dot product multiplcation:

In [20]:
A = np.random.randn(4,2)
B = np.random.randn(4,2)

C = np.dot(A, B.T)

array([[ -2.29762017e+00,   4.10010440e-01,  -3.26599498e+00,
         -1.34670355e+00],
       [ -2.50297806e-02,  -2.03079436e-03,   9.42184453e-02,
         -5.72629025e-02],
       [  4.98975234e+00,  -8.32505090e-01,   5.93578130e+00,
          3.30430273e+00],
       [  4.12494364e+00,  -6.94982915e-01,   5.04215538e+00,
          2.68726387e+00]])

## Solving a Linear System

We are attempting to solve for $x$ in the following equation:

\begin{equation}
Ax = B
\end{equation}

The first thing we'll do is to multiply the inverse of $A$ on both sides.

\begin{equation}
A^{-1}Ax = A^{-1}B
\end{equation}

In [26]:
A = np.random.randn(10,10)
B = np.random.random((10,2))

A_inv = np.linalg.inv(A)

x = np.linalg.inv(A).dot(B)
x

array([[ 2.30862421, -0.30557336],
       [ 1.15786754,  0.08031649],
       [-4.67004227, -0.27130516],
       [ 2.52921365,  0.07093559],
       [ 2.25518559, -0.04072269],
       [-0.38726799, -1.07289578],
       [ 0.6289396 , -0.91656997],
       [-3.29792535,  0.45252332],
       [ 2.37130048,  0.25784228],
       [-1.03709568, -0.12186669]])

You can also use numpy's own `np.linalg.solve()` method. In fact, this is considered preferable:

In [28]:
np.linalg.solve(A, B)

array([[ 2.30862421, -0.30557336],
       [ 1.15786754,  0.08031649],
       [-4.67004227, -0.27130516],
       [ 2.52921365,  0.07093559],
       [ 2.25518559, -0.04072269],
       [-0.38726799, -1.07289578],
       [ 0.6289396 , -0.91656997],
       [-3.29792535,  0.45252332],
       [ 2.37130048,  0.25784228],
       [-1.03709568, -0.12186669]])

You can see that the runtime for `np.linalg.solve()` is less than that of the manual `np.linalg.inv()` and `np.linalg.dot()` functions.

In [34]:
T = 10000
start = datetime.now()
for i in range(T):
    np.linalg.solve(A,B)
    
print("Numpy solve: {}".format(datetime.now() - start))

Numpy solve: 0:00:00.193862


In [35]:
start = datetime.now()
for i in range(T):
    A_inv = np.linalg.inv(A)
    np.linalg.inv(A).dot(B)

print("Using inverse and dot product: {}".format(datetime.now() - start))

Using inverse and dot product: 0:00:00.329607


## Solving Word Problems Using Numpy

The unit cost of a small Toyota is **\$15,000**. The unit cost of a truck is **\$42,000**. If a total of 11 cars were sold and a revenue of **\$435,000** was generated, how many cars of each type were sold? 

This can be represented as a system of equations:


\begin{equation}
X_1 + X_2 = 11
\end{equation}
\begin{equation}
15000X_1 + 42000X_2 = 435000
\end{equation}

\begin{bmatrix}
    1 & 1 \\
    15000 & 42000 \\
\end{bmatrix}

This is multiplied with

\begin{bmatrix}
    x_1 \\
    x_2 \\
\end{bmatrix}

In order to obtain

\begin{bmatrix}
    11 \\
    435000 \\
\end{bmatrix}

In [39]:
A = np.array([[1,1], [15000, 42000]])
B = np.array([[11], [435000]])

In [53]:
x = np.linalg.solve(A, B)
x = x.flatten()
print("There were {} Toyotas and {} trucks sold.".format(x[0], x[1]))

There were 1.0 Toyotas and 10.0 trucks sold.
