In [30]:
import numpy as np

We first generate a bunch of numbers to play with- in this case, a range from 0 to 19.

In [33]:
data = list(range(20))
print(f"The data has a mean of {np.mean(data)} and a \
variance of {np.var(data)}.")

The data has a mean of 9.5 and a variance of 33.25.


In [34]:
BOOTSTRAP_SAMPLES = 10 # the number of resamples to generate
SAMPLE_SIZE = 10 # the number of samples per resample

$E({\bar{\theta_{B}}})$ is defined as the expected value of the **resampled data**, with $B$ defined as the number of resamples generated.

If there is no bias in the sampling (the algorithm or human has a preference for picking smaller numbers, for instance), then **$E({\bar{\theta_{B}}}) = \theta$**. In other words, the sample mean equals the mean of the data.

How do we know this? Well, we know that $E({\bar{\theta_{B}}}) = E\{\sum_{i=0}^{B}{\frac{1}{B}\hat{\theta_{i}}}\}$.

If each of the $\hat{\theta_{i}}$ estimates has been arrived at with no bias in sampling, then we know it should equal $\theta$. Thus, we can rewrite this to $ \frac{1}{B}BE[\hat{\theta_{i}}]$. This cancels out to $E[\hat{\theta_{i}}]$.

In [35]:
for i in range(BOOTSTRAP_SAMPLES):
    print(np.random.choice(data, SAMPLE_SIZE, replace=True))

[17 12 17 14 14  5 11 17  2 10]
[ 1  2 16  4  2 19 13  3  5 15]
[ 8 12 10 12 10 17 19  4  6  5]
[17  7  4 17 16 14  5 17  3 10]
[16  9 12 13 19  3  9 16  5  8]
[14  1 13  7  9 11  8 13 11 16]
[ 1 11 13  3 11 15  8  6  0 17]
[ 6  5 16 12 13 14  7 12  8 12]
[15 11 19 11  2  1 16 15 12  4]
[19  8 14  8  3 16  8 19  5 19]


Because we set `replace=True`, we sample **with replacement**. This means that the algorithm picks a number from `data`, records the result, and places that number back into the pool of numbers to choose from. Thus, **we are able to get identical numbers in the resampled set**.